#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

FONT_FILE="./noto_sans_cjk_18_regular.h"

font_id() {
  python3 - "$FONT_FILE" <<'PY'
import hashlib
import sys

value = int(hashlib.sha256(open(sys.argv[1], "rb").read()).hexdigest(), 16)
print(value % (2 ** 32) - (2 ** 31))
PY
}

ID="$(font_id)"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""
echo "#define BOOKERLY_12_FONT_ID (${ID})"
echo "#define BOOKERLY_14_FONT_ID (${ID})"
echo "#define BOOKERLY_16_FONT_ID (${ID})"
echo "#define BOOKERLY_18_FONT_ID (${ID})"
echo "#define NOTOSANS_12_FONT_ID (${ID})"
echo "#define NOTOSANS_14_FONT_ID (${ID})"
echo "#define NOTOSANS_16_FONT_ID (${ID})"
echo "#define NOTOSANS_18_FONT_ID (${ID})"
echo "#define OPENDYSLEXIC_8_FONT_ID (${ID})"
echo "#define OPENDYSLEXIC_10_FONT_ID (${ID})"
echo "#define OPENDYSLEXIC_12_FONT_ID (${ID})"
echo "#define OPENDYSLEXIC_14_FONT_ID (${ID})"
echo "#define UI_10_FONT_ID (${ID})"
echo "#define UI_12_FONT_ID (${ID})"
echo "#define SMALL_FONT_ID (${ID})"
